make: my-cat my-grep my-zip my-unzip

my-cat:
	gcc -o my-cat my-cat.c -Wall -Werror

my-grep:
	gcc -o my-grep my-grep.c -Wall -Werror

my-zip:
	gcc -o my-zip my-zip.c -Wall -Werror

my-unzip:
	gcc -o my-unzip my-unzip.c -Wall -Werror

clean:
	rm -f my-cat my-grep my-zip my-unzip
